### ISSUE TITLE
Validation code searches for schema  in an non-existing folder

### ISSUE THREAD

**Issue by pedrocamargo** [e-lo/GMNSpy#13]
The code is currently expecting the schema files to be outside the package folder, which only works well in "development mode", as installing it from PyPI results in errors when using it.

![image](https://user-images.githubusercontent.com/7377666/193957979-95c198ad-c845-47fd-9a35-1d5d275af6fc.png)

Ideally, the code would have the specs shipped with them and allow for use independent from cloning the repository

**Comment by e-lo** [comment]
Good point. I think I was originally hoping that there would be an officially maintained schema that we could point to instead of maintaining it locally.

I see that there is now a Specification folder at https://github.com/zephyr-data-specs/GMNS/blob/master/Specification/

Questions:

1. Does it even make sense to have this repo/project separate from the official `GMNS` repo?
2. If so, is there any reason why we shouldn't just pull from the official `GMNS` repo?

**Comment by pedrocamargo** [comment]
I would prefer to have the repo's separately and connect them through CI pipelines, releasing a new version of GMNSpy any time there is a new push to master on the GMNS specification happens.

That said, keeping them under the same "roof" would facilitate things a lot...
